forge flatten contracts/BSCValidatorSet.sol > contracts/flattened/BSCValidatorSet.sol
forge flatten contracts/GovHub.sol > contracts/flattened/GovHub.sol
forge flatten contracts/RelayerHub.sol > contracts/flattened/RelayerHub.sol
forge flatten contracts/RelayerIncentivize.sol > contracts/flattened/RelayerIncentivize.sol
forge flatten contracts/SlashIndicator.sol > contracts/flattened/SlashIndicator.sol
forge flatten contracts/SystemReward.sol > contracts/flattened/SystemReward.sol
forge flatten contracts/TendermintLightClient.sol > contracts/flattened/TendermintLightClient.sol
forge flatten contracts/TokenHub.sol > contracts/flattened/TokenHub.sol
forge flatten contracts/CrossChain.sol > contracts/flattened/CrossChain.sol
forge flatten contracts/TokenManager.sol > contracts/flattened/TokenManager.sol
forge flatten contracts/Staking.sol > contracts/flattened/Staking.sol